# Generated by Django 3.1.6 on 2021-03-03 18:00

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CosplayRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Наименование темы')),
                ('slug', models.SlugField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Рубрика коллекции',
                'verbose_name_plural': 'Рубрики коллекций',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Наименование изображения')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=apps.core.models.upload_path_image, verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание изображения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Имя')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=apps.core.models.upload_path_model_photo, verbose_name='Фото')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('stars_count', models.IntegerField(default=1, null=True, verbose_name='Количество звёзд у модели')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=500, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.image')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Image_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Наименование коллекции')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_collections', to='core.models')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.cosplayrubric')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='image',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image_collection'),
        ),
        migrations.CreateModel(
            name='CosplayBlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Наименование поста')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('collections', models.ManyToManyField(to='core.Image_Collection')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('id',),
            },
        ),
    ]
