# Generated by Django 3.1.6 on 2021-02-25 14:11

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='surname')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=apps.core.models.upload_path_model_photo, verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('stars_count', models.IntegerField(default=1, null=True, verbose_name='Количество звёзд у модели')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Image_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Наименование коллекции')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.models', verbose_name='collections')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекции',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Наименование изображения')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to=apps.core.models.upload_path_image, verbose_name='Изображение')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание изображения')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.image_collection')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'изображения',
                'ordering': ('id',),
            },
        ),
    ]
