# Generated by Django 3.1.6 on 2021-03-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_collection',
            old_name='theme',
            new_name='rubric',
        ),
    ]
