# Generated by Django 3.1.6 on 2021-02-25 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='models',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='models',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='image_collection',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.models'),
        ),
    ]
