# Generated by Django 3.1.6 on 2021-03-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210307_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='for_title',
            field=models.BooleanField(default=False),
        ),
    ]
