# Generated by Django 3.1.6 on 2021-03-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210304_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AddField(
            model_name='image_collection',
            name='description',
            field=models.CharField(blank=True, max_length=300, verbose_name='Описание коллекции'),
        ),
    ]
