# Generated by Django 3.1.6 on 2021-03-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_image_for_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
