# Generated by Django 3.1.6 on 2021-03-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210307_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosplaypost',
            name='recommended',
            field=models.BooleanField(default=False),
        ),
    ]
