# Generated by Django 3.1.6 on 2021-03-04 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20210304_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='image_collection',
            name='likes',
            field=models.ManyToManyField(related_name='collection_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
