# Generated by Django 3.1.6 on 2021-03-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image_collection_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_collection',
            name='likes',
        ),
    ]
