# Generated by Django 3.1.6 on 2021-03-15 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cosplaypost_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='rubric',
        ),
        migrations.AlterField(
            model_name='cosplaypost',
            name='title',
            field=models.CharField(blank=True, max_length=60, validators=[django.core.validators.MinLengthValidator(40, message='Length has to be a minimum 40')], verbose_name='Наименование поста'),
        ),
    ]
